emulator.xml
* Emulator ICS - Points to the correct Bionic branch
* Emulator ICS - Downloads gcc-4.8 Android based toolchain
Let's change the ICS emulator first, and if all goes well, I'll update the rest of ICS devices.
=> Bug 1056337 - Upgrading B2G ICS toolchain

hamachi.xml
* Hamachi manifest changed in order to point to our new Bionic fork and download gcc-4.8 based toolchain.
=> Bug 1056337 - Upgrading B2G ICS toolchain to gcc-4.8

keon.xml, peak.xml
* Changed Bionc repo to point to our fixed fork for Keon and Peak
* Added gcc-4.8 based toolchain for Keon and Peak
=> Bug 1121593 - Support GCC-4.8 for Peak and Keon

rpi.xml
* Change manifest to download gcc-4.8 based toolchain
=> Bug 1123092 - [RPi] Upgrade toolchain to gcc.4.8

flatfish.xml
* Change manifest to download gcc-4.8 toolchain
Change-Id: Ic64c1972ac8af00bbc19e97892272cf515661eb4
=> Bug 1122932 - [flatfish] Upgrade toolchain to gcc-4.8

pandaboard.xml
Negatus is not required and requires external dependencies (NSPR)
for building. This commit removes it from the manifest.
Change-Id: Ic558b82bcf4e2e08098ee045015412d170359f48
=> Bug 1127371: Remove Negatus from Pandaboard manifest

emulator.xml
Please see [bug 1128837](https://bugzilla.mozilla.org/show_bug.cgi?id=1128837).
=> Bug 1128837 - Update emulator hardware/ril to branch b2g-ril_v7. r=seinlin

base-kk-caf.xml
Change-Id: Ice95ce37cdf48df49a3732ebac872f757eb9ae7e
=> Bug 1131892 - Override libhardware_legacy to fix device crashed by wifi.

nexus-5-l.xml
Change-Id: I72f9b0a0115f70aedc5620174dc4f96cbf1d701c
The hash revision is not in the repo, so it causes failure.  Replaced with a hash that is in the repo.
=> change rev for f2fs-tools

shinano.xml
=> Bug 1141635 - Add external/init_sh (recovery support for aries/shinano)

wasabi.xml
Apparently the RIL team is still using it. This brings wasabi back until we can upgrade them to something more modern.
=> Bug 1150397 - Temporarily bring wasabi back

base-l-aosp.xml, base-l.xml, nexus-5-l.xml
Reverts mozilla-b2g/b2g-manifest#315 because not all dependent patches landed with review.
=> Revert "Bug 1147266 - Update nexus-5-l manifest to b2g-5.1.0_r1. r=mwu"

flame-kk.xml
To apply change in device/t2m/flame/BoardConfig.mk
Change-Id: Ia1194abc533f8a70113ea99cf9413f188cfb920e
=> Bug 1155035 - Set v2.0's device-flame to kitkat for flame-kk

run_travis_tests.sh
mozharness/configs/b2g_bumper/aries.py has been removed in [bug 1144994](https://bugzilla.mozilla.org/show_bug.cgi?id=1144994), we need
to do corresponding change in b2g-manifest/run_travis_tests.sh as well.
=> Bug 1165276 - Don't run the b2g-manifest travis tests on aries. r=catlee

emulator.xml
Please see [bug 1128837](https://bugzilla.mozilla.org/show_bug.cgi?id=1163968).
=> Bug 1163968 - Update emulator-ics external/qemu to branch b2g-ics. r=seinlin

emulator-l.xml
Please see [bug 1181481](https://bugzilla.mozilla.org/show_bug.cgi?id=1181481).
=> Bug 1184418 - [emulator-l] Switch external/qemu to b2g-studio-1.3 branch

emulator-jb.xml
Change-Id: I99b34784fd1c90cda25368372fc187941ad97f46
=> Bug 1087161 - Add gcc-4.9 toolchain to JB devices (v2.2). r=mwu

emulator-kk.xml, emulator-l.xml
Please see [bug 1134982](https://bugzilla.mozilla.org/show_bug.cgi?id=1134982).
=> Bug 1134982 - Switch hardware/ril to proper branch for emualtor-kk and emulatro-l

flame-l.xml
In Part 2, the policies form device/qcom/sepolicy have been moved to device/t2m/flame, therefore they are deleted here.
=> Part 3: Bug 1180216 - Use forked external/sepolicy, remove qcom sepolicy r=seinlin

shinano.xml
Change-Id: I735b2b9830ea9ded8e696891ef30aae479970e32
=> Bug 1136512 - Sony Z3C - nfcd should build with Z3 compatiable libnfc-nci library

emulator-jb.xml, emulator-kk.xml, emulator-l.xml, emulator.xml, flame-kk.xml, flatfish.xml, galaxy-nexus.xml, galaxy-s2.xml, hamachi.xml, helix.xml, keon.xml, nexus-4-kk.xml, nexus-5-l.xml, nexus-5.xml, nexus-6-l.xml, nexus-s-4g.xml, nexus-s.xml, otoro.xml, pandaboard.xml, peak.xml, rpi.xml, shinano.xml, sony-aosp-l.xml, tarako.xml, vixen.xml, wasabi.xml
manifest is pointing to a nonexisiting repo for gecko; local building is broken without a point to the right location.
based on an irc conversation between hal and fabrice, here's a patch.
=> Bug 1233351 - Manifest fixes to gecko to point to gmo/integration/gecko-dev

galaxy-nexus.xml
CAF is considered more reliably and faster than Linaro, so we now fetch
repositories for galaxy-nexus by default from CAF.
=> Bug 1236503: Fetch repositories for galaxy-nexus from CAF

base-jb.xml, base-kk.xml, base-l.xml, base.xml, flatfish.xml, vixen.xml
Sensorsd uses libfdio for it's event loop. The library has to be present
for all targets.
=> Bug 1196221: Clone libfdio for all targets

fairphone2.xml
Instead of doing this manualy:
cd frameworks/native && git checkout -b caf_atomic_cpp
caf/LA.BF.1.1.1_rb1.18 && curl -L
https://github.com/mozilla-b2g/platform_frameworks_native/pull/1.patch | git
am && cd ~/B2G
./repo sync
The caf/LA.BF.1.1.1_rb1.18 got forked to b2g-fp2 branch
- tested 25. Aug. 2016
=> Bug 1294725 - Fairphone 2 needs special caf repo r=gerard-majax
