mozilla-b2g/b2g-manifest

galaxy-nexus.xml, galaxy-s2.xml, hamachi.xml, helix.xml, leo.xml, nexus-s-4g.xml, nexus-s.xml
* Changed manifest files to upgrade the toolchain for all the important ICS devices
=> Bug 1056337 - Upgrade B2G ICS toolchain for Gecko

nexus-5-l.xml
Change-Id: Ice2f6e0d44825ef7fb91cc9c1d30ca20dfe3af4c
=> Bug 1117662 - enable VENUS on 8974 and 8226. r=kli

dolphin-512.xml
Change-Id: I82d4db65740b18a7c60ed0cdf1def9b8b779e05c
=> Bug 1120745 - create a symbolic link for dolphin512.

flame-kk.xml, flame.xml
Change-Id: I6ed8006dcf9432ed5a07c8996c457e989beeba10
=> Bug 1120841 - Add libnfc-pn547 to flame and flame-kk manifests. r=mwu

emulator-kk.xml
Please see [bug 1128837](https://bugzilla.mozilla.org/show_bug.cgi?id=1128837).
=> Bug 1128837 - Update emulator-kk hardware/ril to branch master. r=seinlin

base-l.xml, emulator-l.xml, emulator-x86-l.xml
Change-Id: I899192c7d2bd72f930aebb445ed4b57dc45af55a
=> Bug 1116074 - Add emulator-l and emulator-x86-l.

emulator.xml
https://bugzilla.mozilla.org/show_bug.cgi?id=1113271
=> Bug 1113271 - Fix stagefright FLACParser

nexus-5-l.xml
Change-Id: Ideb4d50f993819bdabceba32f2e2d82aeec9e5c8
=> Bug 1120780 - Switch to fork of hardware/qcom/display on N5

nexus-5-l.xml
This reverts commit 1ebc1b5fabb250ced6a53f7db4cf4a7998ba338c.
=> Revert "Bug 1117662 - enable VENUS on 8974 and 8226. r=kli"

nexus-5-l.xml
Change-Id: I438526e1c38f3b22a66eb25f3eca33a8302941be
=> Bug 111762 revert change

aries.xml
This patch allows mozharness to build aries devices.
=> Bug 1134722: Add a symbolic link to aries manifest.

base-l-aosp.xml, base-l.xml, nexus-5-l.xml
Change-Id: Iffe0b85e8bb65acc7f38c7b6c1fdcc881fb367ae
=> Bug 1147266 - Update nexus-5-l manifest to b2g-5.1.0_r1. r=mwu

emulator-l.xml
Change-Id: I45a3f3f31dd2bec6ca1fe9f12930e3720da59da3
=> Bug 1149387 - Update emulator-l manifest to b2g-5.1.0_r1. r=tdz

nexus-5-l.xml
Reverts mozilla-b2g/b2g-manifest#320 for landing without driver approval.
=> Revert "Bug 1147266 - Update nexus-5-l manifest to b2g-5.1.0_r1. r=mwu"

emulator-l.xml
Reverts mozilla-b2g/b2g-manifest#316
=> Revert "Bug 1149387 - Update emulator-l manifest to b2g-5.1.0_r1. r=tdz"

base-l-aosp.xml, base-l.xml, emulator-l.xml, nexus-5-l.xml
Change-Id: Iffe0b85e8bb65acc7f38c7b6c1fdcc881fb367ae
=> Bug 1149387- Update base-l and related manifests to b2g-5.1.0_r1.

emulator-kk.xml, emulator-l.xml
Change-Id: I2b89e80650758e3cb955f40c0482d5c85aa0367b
=> Bug 1001261 - Update emulator-kl/l to use b2g forked wpa_supplicant.

flame-kk.xml
For branch v2.2, update device-flame revision to "kitkat" like master
Change-Id: I6f6583e1ebdd3df77196c598c694151a527fa25b
=> Bug 1155035 - Update device-flame revision to "kitkat"

flame-kk.xml
To apply change in device/t2m/flame/BoardConfig.mk
Change-Id: If5d31621078d609159e70fa623751e4dcab2cbdb
=> Bug 1155035 - Set v2.1's device-flame to kitkat for flame-kk

emulator-kk.xml
Change-Id: Ib2ae7dde8c2adc0406a89da209b627c190c519a1
=> Bug 964697 - (emulator-NFC) B2G Emulator: NFC support in KK

shinano.xml
Change-Id: I218b9012818e529684384a26d7837284a93e1be7
=> Bug 1154690 - Switch bcmdhd to 1.88.57.4 r=mwu

aries-l.xml, shinano-l.xml
Change-Id: I72504d5d5e35ef136204bb7b75964eccfb55923c
=> Add manifest for aries-l and shinano-l.

shinano.xml
https://bugzilla.mozilla.org/show_bug.cgi?id=1171201
=> Bug 1171201 - Switch platform/hardware/qcom/display from caf to b2g

base-jb.xml
Change-Id: I16e1aeedb7b22d730c9f88b2c61106cba1a44d56
=> Bug 1087161 - Add gcc-4.9 toolchain to JB devices. r=mwu

emulator-jb.xml
Change-Id: I99b34784fd1c90cda25368372fc187941ad97f46
=> Bug 1087161 - Add gcc-4.9 toolchain to JB devices (v2.1s). r=mwu

flamingo-l.xml, tianchi-l.xml, yukon-l.xml
Signed-off-by: Adam Farden <adam@farden.cz>
=> Bug 1175254 - Sony msm8226: tianchi and flamingo devices r=gerard-majax

flame-kk.xml
https://bugzilla.mozilla.org/show_bug.cgi?id=1085593
=> Bug 1085593 - Do not optimize layers when layer has multiple visible regions

base-kk.xml
Change-Id: I88b7ae131324c20c1a813687fa81ef08654b927f
=> Bug 1194532: upgrade mdnsd to fix FD leaks that cause CPU spin. r=mwu

emulator-kk.xml, flame-kk.xml, shinano.xml
Change-Id: Id97b1ccab24fe2dfe9ec16cee11a7675878abc8f
=> Bug 1209892: Update KK manifests to use mozilla-b2g bionic. r=echen

flame-kk.xml
https://bugzilla.mozilla.org/show_bug.cgi?id=1221850
=> Bug 1221850 - Use mozilla-b2g/platform_frameworks_av on flame-kk

run_travis_tests.sh
See bug for patch which creates that file.
=> bug 1227349 - Update for new b2g-ota branch

sony-aosp-l.xml
=> Adding xPeria T3 (seagull) - bug 1221152

fairphone2.xml
Change-Id: I14e8a929ebbc0fac25ab865c00e4533872dc2ebd
=> Bug 1233685 - Fairphone 2 manifest file added

base-l-aosp.xml, base-l.xml, sony-aosp-l.xml
Signed-off-by: Adam Farden <adam@farden.cz>
=> Bug 1226363 - Rebase our L forks to 5.1.1_r29 r=gerard-majax

sony-aosp-l.xml
Change-Id: I8d1a32a9bfb7ea187f654bdcd88dc23805dac945
=> Bug 1236536 - Add Camera HAL for Sony devices r=mwu

rpi2b-l.xml
Change-Id: Ib6e6f36312e3eb759f2f2e8ced148216aeac660c
=> Bug 1242468 - Only pull arm-eabi-4.7 r=_AtilA_

rpi2b-l.xml
Change-Id: I47fd9b8b36b9f2794e3cee5bf48aa71ccba2d64b
=> Bug 1243306 - Keep arm-eabi-4.8 and clone-depth=1 for arm-eabi-4.7 r=_AtilA_

rpi2b-l.xml
modified branches
Change-Id: I1fbd7151eda2168ac4bf66a105f16b0ec16b4796
=> [RPi2B] Change the branch of mesa and gralloc to point to our

shinano.xml
Change-Id: I012ee7e784deaaabddf71c5ad7a4d2f2dda23ae5
=> Bug 1252187 - Add gcc-4.8 android toolchain to Aries-KitKat

flame-kk.xml
for flame-kk.
Change-Id: Id6407ed4038a21a4fd6800190160910860de8165
=> Bug 1252430 - Add Linux and Mac gcc-4.8 based google toolchains

base-kk.xml
Change-Id: I75b8154b3aecb6d6d5023c9a32e218c60798b0de
=> Bug 1087161 - Add gcc-4.9 toolchain to KK devices r=gerard-majax

shinano.xml
Change-Id: I97f5ae287a2823b2d47efab529bd666edfa54852
=> Bug 1253600 - Add nginx repo r=me

fairphone2.xml
=> Bug 1294725 - Fairphone 2 needs special caf repo xy r=gerard-majax
